Make Sibernetic build work for modern Mac

diff --git a/makefile.OSX b/makefile.OSX
--- a/makefile.OSX
+++ b/makefile.OSX
@@ -1,6 +1,13 @@
 TARGET = Sibernetic
 RM := rm -rf
 
+VENV_DIR ?= ./venv
+VENV_PYTHON := $(VENV_DIR)/bin/python
+HOST_PYTHON := $(shell command -v python3 2>/dev/null || command -v python 2>/dev/null)
+PYTHON ?= $(if $(wildcard $(VENV_PYTHON)),$(VENV_PYTHON),$(HOST_PYTHON))
+
+CXX ?= $(shell command -v g++ 2>/dev/null || command -v clang++ 2>/dev/null)
+
 # All of the sources participating in the build are defined here
 SOURCES = src/owSignalSimulator.cpp \
 src/owVtkExport.cpp \
@@ -25,22 +32,35 @@ OBJECTS += $(BINARYTESTDIR)/owPhysicTest.o
 
 CPP_DEPS = $(OBJECTS:.o=.d)
 
-# Change these to set the different python directories
-PYTHONHEADERDIR = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/
-PYTHONLIBDIR = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/
-PYTHONFRAMEWORKDIR = /Library/Frameworks/
+PYTHON_CFLAGS := $(shell if [ -n "$(PYTHON)" ]; then "$(PYTHON)" -c "import sysconfig; print('-I'+sysconfig.get_paths()['include'])"; fi)
+PYTHON_LDFLAGS := $(shell if [ -n "$(PYTHON)" ]; then "$(PYTHON)" -c "import sysconfig; libdir=sysconfig.get_config_var('LIBDIR'); ver=sysconfig.get_config_var('VERSION'); print('-L%s -Wl,-rpath,%s -lpython%s' % (libdir, libdir, ver))"; fi)
 
-LIBS := -framework Python -framework OpenGL -framework GLUT -framework OpenCL
+LIBS := -framework OpenGL -framework GLUT -framework OpenCL
 
 
 # All Target
-all: $(TARGET)
+all: bootstrap $(TARGET)
+
+bootstrap:
+	@if [ -z "$(CXX)" ] || ! command -v "$(CXX)" >/dev/null 2>&1; then \
+		echo "Error: no usable C++ compiler found (checked CXX='$(CXX)')."; \
+		echo "Hint: install Xcode command line tools or set CXX to a valid compiler path."; \
+		exit 1; \
+	fi
+	@if [ ! -x "$(VENV_PYTHON)" ]; then \
+		if [ -z "$(HOST_PYTHON)" ]; then \
+			echo "Error: no Python interpreter found (expected python3 or python in PATH)."; \
+			exit 1; \
+		fi; \
+		echo "Creating virtual environment at $(VENV_DIR)"; \
+		"$(HOST_PYTHON)" -m venv "$(VENV_DIR)"; \
+	fi
 
 # Tool invocations
-$(TARGET): $(OBJECTS)
+$(TARGET): bootstrap $(OBJECTS)
 	@echo 'Building target: $@'
 	@echo 'Invoking: clang C++ Linker'
-	g++ -std=c++14 -L/usr/lib -F$(PYTHONFRAMEWORKDIR) -L$(PYTHONLIBDIR) -o $(BUILDDIR)/$(TARGET) $(OBJECTS) $(LIBS)
+	$(CXX) -std=c++14 -L/usr/lib $(PYTHON_LDFLAGS) -o $(BUILDDIR)/$(TARGET) $(OBJECTS) $(LIBS)
 	@echo 'Finished building target: $@'
 	@echo ' '
 
@@ -51,7 +71,7 @@ $(BINARYDIR)/%.o: $(SRCDIR)/%.cpp
 	@echo 'Invoking: clang C++ Compiler'
 #### use this to compile against homebrew installed python
 #### change version number as necessary (2.7.n)
-	g++ -std=c++14 -O3 -Wall -c -I$(PYTHONHEADERDIR) -I$(INCDIR) -framework OpenCL -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
+	$(CXX) -std=c++14 -O3 -Wall -c $(PYTHON_CFLAGS) -I$(INCDIR) -framework OpenCL -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
 	@echo 'Finished building: $<'
 	@echo ' '
 
@@ -60,5 +80,5 @@ clean:
 	-$(RM) $(OBJECTS)$(CPP_DEPS) $(BUILDDIR)/$(TARGET)
 	-@echo ' '
 
-.PHONY: all clean dependents
+.PHONY: all bootstrap clean dependents
 .SECONDARY:
